apiVersion: v3
kind: service
metadata:
  name: hss-networks
  description: HSS demo service - networks
  tags:
    - team:hss-network-team
    - owner:et
    - customer:hss
    - env:demo
    - business-unit:infrastructure
spec:
  type: web
  lifecycle: production
  tier: "2"
