apiVersion: v3
kind: service
metadata:
  name: hss-databases
  description: HSS demo service - databases
  tags:
    - team:hss-database-team
    - owner:et
    - customer:hss
    - env:demo
    - business-unit:infrastructure
spec:
  type: datastore
  lifecycle: production
  tier: "2"
